### PR TITLE
Updated README.md for Hacktoberfest

### PR DESCRIPTION
**Pull request by PokeAcer549**
Referencing the issue regarding this; I added description for each script and the Apache license with the name you specified on your GitHub.

### CODE REVIEW

**Comment by PokeAcer549** [comment]
I left out the contributing session; I understand if you don't accept it.

**Comment by andreybleme** [comment]
@PokeAcer549 thanks for helping. I'll keep the issue open, because you missed the contributing session.

**Comment by PokeAcer549** [comment]
I didn't know what you meant by contributing *session* so I added a *section* stating to add credits in bash scripts, and that they'll be licensed by Apache v2.0

**Comment by andreybleme** [comment]
@PokeAcer549 a contributing session would be somethign like this: https://github.com/andreybleme/protractor-sublime-snippets/blob/master/README.md

**Comment by PokeAcer549** [comment]
Ah, OK.

**Comment by PokeAcer549** [comment]
And added c: (sorry I was watching Bake Off x3)

**Pull request merged**
